security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    users_in_memory: { memory: null }
    app_user_provider:
      entity:
        class: App\Auth\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_auth:
      pattern: ^/api/auth
      security: false

    api:
      pattern: ^/api
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Auth\Service\TokenAuthenticator
      stateless: true  # API should be stateless

    main:
      lazy: true
      provider: app_user_provider


when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
