#### GET request
GET {{host}}/api/client/list
X-API-TOKEN: {{api_token}}

#### GET request
GET {{host}}/api/client/list
X-API-TOKEN: {{api_token}}

#### GET request
GET {{host}}/api/client/self
X-API-TOKEN: {{api_token}}

#### GET request
GET {{host}}/api/client/1

### POST request
POST {{host}}/api/client
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe"
}

### POST request
POST {{host}}/api/client
Content-Type: application/json
X-API-TOKEN: {{api_token}}

{
    "firstName": "Jane",
    "lastName": "Doe"
}
