parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  # Register domains as separate service containers
  App\Auth\:
    resource: '../src/Auth/'
    exclude:
      - '../src/Auth/Entity/'

  App\Transfer\:
    resource: '../src/Transfer/'
    exclude:
      - '../src/Transfer/Entity/'

  # Common services
  App\Service\:
    resource: '../src/Service/'

  App\DataFixtures\:
    resource: '../src/DataFixtures/'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'
