parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Auth\:
    resource: '../src/Auth/'
    exclude:
      - '../src/Auth/Entity/'

  App\Transfer\:
    resource: '../src/Transfer/'
    exclude:
      - '../src/Transfer/Entity/'

  # Common services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'
      - '../src/Auth'
      - '../src/Transfer'
