parameters:
  # Add your parameters here

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Common services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'
      - '../src/Auth'
      - '../src/Transfer'

imports:
  - { resource: 'services/auth.yaml' }
  - { resource: 'services/transfer.yaml' }

